Remove duplicate "content" id
plone/plone.app.registry pull request #84
Opened 2024-05-09 13:54 UTC by szakitibi

There is a duplicate `<article id="content"`>` introduced with the controlpanel.
https://github.com/plone/plone.app.registry/blob/2ffffe69324cc480081e99b1e9553c160ec61d7b/plone/app/registry/browser/templates/records.pt#L20-L25

The `main_template.pt` already has one - see https://github.com/plone/Products.CMFPlone/blob/6.0.11/Products/CMFPlone/browser/templates/main_template.pt#L85.

As a result there is two `<article id="content">` for `portal_registry` controlpanel - view source for https://classic.demo.plone.org/portal_registry.

The problem can be eliminated by changing the id, or using a simple metal tag to fill the slot.

2024-05-09 13:54 UTC, mister-roboto commented
@szakitibi thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-05-09 13:57 UTC, szakitibi commented
The same duplicate id is also present in other default Plone controlpanels:

- Products/CMFPlone/controlpanel/browser/usergroups_groupsoverview.pt
- Products/CMFPlone/controlpanel/browser/usergroups_groupmembership.pt
- ...

2024-05-16 20:18 UTC, davisagli requested changes
@szakitibi Thanks, this fix looks good, but there are 2 things missing before it is ready to merge:
1. Run `tox -e format` to autoformat the file using zpretty
2. Add an entry for the change log (see https://6.docs.plone.org/contributing/index.html#change-log-entry)

2024-05-17 06:14 UTC, mister-roboto commented
Tibor Szakmany your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement How to add more emails to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

2024-05-23 00:07 UTC, davisagli commented
@jenkins-plone-org please run jobs

2024-05-23 00:46 UTC, davisagli approved these changes
Thanks!

2024-05-23 00:46 UTC, merged